name: Deploy to Amazon ECS

on:
  push:
    branches: 
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
          java-version: 17
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml -Dmaven.test.skip=true
      
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
          name: artifact
          path: ./target/gpt_ua-0.0.1.jar

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v4
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: false
          application_name: GPT-UA
          environment_name: Gptua-env
          version_label: ${{ github.sha }}-test
          region: eu-central-1
          deployment_package: gpt_ua-0.0.1.jar
        
        
