name: Deploy to Amazon ECS

on:
  push:
    branches: 
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: mvn clean:package
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v4
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: GPT-UA
        environment_name: Gptua-env
        version_label: ${{ github.sha }}-test
        region: eu-central-1
        deployment_package: gpt_ua/target/gpt_ua-0.0.1.jar
